Repository emdgroup/baybe, pull requests merged in 2023-12, with the labels that each got.

#13 Repo/fix links
  .github/workflows/docs.yml
  .github/workflows/regular.yml
  CONTRIBUTING.md
  README.md
  docs/index.md
  docs/userguide/objective.md
  docs/userguide/userguide.md
  tox.ini
Labels: bug, documentation

#18 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#20 Add Literature References
  CHANGELOG.md
  baybe/utils/dataframe.py
  examples/Backtesting/full_lookup.py
Labels: enhancement

#22 Minor color adjustments
  docs/_static/custom.css
  docs/conf.py
Labels: documentation

#21 Userguide: Constraints and Parameters
  README.md
  baybe/constraints/conditions.py
  docs/conf.py
  docs/userguide/constraints.md
  docs/userguide/parameters.md
  docs/userguide/transfer_learning.md
  docs/userguide/userguide.md
Labels: documentation

#23 Release 0.7.0
  CHANGELOG.md
Labels: repo

#25 Release Sdists
  .github/workflows/release.yml
  CHANGELOG.md
Labels: repo

#26 Release 0.7.1
  CHANGELOG.md
Labels: repo

#6 Hypothesis for parameters
  .gitignore
  CHANGELOG.md
  baybe/exceptions.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/parameters/validation.py
  baybe/utils/basic.py
  baybe/utils/chemistry.py
  examples/Multi_Target/desirability.py
  pyproject.toml
  ruff.toml
  tests/hypothesis_strategies.py
  tests/serialization/test_parameter_serialization.py
  tests/test_parameters.py
  tests/validation/__init__.py
  tests/validation/test_parameter_validation.py
Labels: tests

#54 Mypy for targets
  CHANGELOG.md
  baybe/objective.py
  baybe/simulation.py
  baybe/targets/__init__.py
  baybe/targets/base.py
  baybe/targets/enum.py
  baybe/targets/numerical.py
  baybe/targets/transforms.py
  baybe/utils/__init__.py
  baybe/utils/dataframe.py
  examples/Backtesting/multi_target.py
  examples/Multi_Target/desirability.py
  mypy.ini
  tests/conftest.py
  tests/test_targets.py
Labels: typing

#55 Mypy for intervals
  CHANGELOG.md
  baybe/parameters/numerical.py
  baybe/targets/numerical.py
  baybe/utils/interval.py
  mypy.ini
  tests/test_deprecations.py
Labels: typing

#59 Documentation tests
  CHANGELOG.md
  docs/userguide/constraints.md
  ruff.toml
  tests/docs/__init__.py
  tests/docs/test_docs.py
  tests/docs/test_examples.py
  tests/docs/utils.py
  tests/test_examples.py
Labels: tests

#67 Fix type alias and generic in documentation
  CHANGELOG.md
  docs/conf.py
  docs/scripts/convert_code_to_documentation.py
  docs/templates/custom-attribute-template.rst
  docs/templates/custom-module-template.rst
Labels: documentation
