Repository emdgroup/baybe, pull requests merged in 2024-08, with the labels that each got.

#328 Integrate Polars
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  baybe/_optional/info.py
  baybe/_optional/polars.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/searchspace/discrete.py
  docs/conf.py
  docs/userguide/envvars.md
  mypy.ini
  pyproject.toml
  tests/conftest.py
  tests/constraints/test_constraints_polars.py
  tox.ini
Labels: enhancement, new feature

#329 Rearrange TOC in sidebar
  docs/index.md
Labels: documentation

#322 Add Example for Dynamic Campaign Stopping
  CHANGELOG.md
  baybe/simulation/scenarios.py
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Hooks/probability_of_improvement.py
Labels: documentation, new feature

#330 Conditional solver selection
  CHANGELOG.md
  baybe/surrogates/gaussian_process/core.py
Labels: bug

#331 Integrate Hook Examples
  CHANGELOG.md
  baybe/simulation/scenarios.py
  baybe/utils/botorch_wrapper.py
  baybe/utils/plotting.py
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Hooks/campaign_stopping_dark.svg
  examples/Custom_Hooks/campaign_stopping_light.svg
  examples/Custom_Hooks/probability_of_improvement.py
  examples/Custom_Hooks/probability_of_improvement_dark.svg
  examples/Custom_Hooks/probability_of_improvement_light.svg
  mypy.ini
Labels: documentation, new feature

#333 Update Pictures for Release
  examples/Backtesting/botorch_analytical_dark.svg
  examples/Backtesting/botorch_analytical_light.svg
  examples/Backtesting/full_lookup_dark.svg
  examples/Backtesting/full_lookup_light.svg
  examples/Transfer_Learning/backtesting_dark.svg
  examples/Transfer_Learning/backtesting_light.svg
  examples/Transfer_Learning/basic_transfer_learning_dark.svg
  examples/Transfer_Learning/basic_transfer_learning_light.svg
Labels: release

#332 Release 0.10.0
  CHANGELOG.md
  baybe/campaign.py
  baybe/deprecation.py
  baybe/recommenders/base.py
  baybe/recommenders/deprecation.py
  baybe/recommenders/meta/base.py
  baybe/strategies/__init__.py
  baybe/strategies/deprecation.py
  baybe/targets/base.py
  baybe/utils/interval.py
  docs/templates/custom-module-template.rst
  tests/test_deprecations.py
Labels: release

#325 Surrogate interface
  CHANGELOG.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/searchspace/core.py
  baybe/surrogates/_adapter.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/utils/scaling.py
  tests/test_scaling.py
Labels: enhancement, refactor

#337 Mypy for surrogates
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/gaussian_process/presets/core.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/surrogates/linear.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  docs/conf.py
  mypy.ini
Labels: typing

#342 Add py.typed
  CHANGELOG.md
  baybe/py.typed
Labels: repo

#323 Lockfile for doc generation
  .github/workflows/ci.yml
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  pyproject.toml
  tox.ini
Labels: documentation, enhancement, repo

#259 Fix parameter value conversion
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/parameters/categorical.py
  baybe/parameters/numerical.py
  baybe/utils/conversion.py
  pyproject.toml
  tests/validation/test_parameter_validation.py
Labels: bug

#336 Improve FPS
  CHANGELOG.md
  baybe/utils/sampling_algorithms.py
  tests/utils/test_sampling_algorithms.py
Labels: enhancement

#338 Refactor Surrogates
  CHANGELOG.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/exceptions.py
  baybe/parameters/base.py
  baybe/parameters/numerical.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/scaler.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/_adapter.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/gaussian_process/presets/core.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/surrogates/gaussian_process/presets/edbo.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  baybe/utils/dataframe.py
  baybe/utils/scaling.py
  docs/conf.py
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Hooks/probability_of_improvement.py
  examples/Custom_Surrogates/Custom_Surrogates_Header.md
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  mypy.ini
  ruff.toml
  streamlit/initial_recommender.py
  streamlit/surrogate_models.py
  tests/test_continuous.py
  tests/test_custom_surrogate.py
  tests/test_deprecations.py
  tests/test_scaling.py
  tests/test_searchspace.py
Labels: enhancement, new feature, refactor

#354 Silence mypy type-abstract errors
  baybe/campaign.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  mypy.ini
Labels: typing

#351 Hotfix: Remove python version in tox docs calls
  .github/workflows/ci.yml
  tox.ini
Labels: bug, repo

#339 Fix local doc building
  baybe/simulation/scenarios.py
  docs/conf.py
  docs/scripts/build_documentation.py
  tox.ini
Labels: documentation

#340 `MIN` mode via acquisition function
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/targets/numerical.py
  streamlit/surrogate_models.py
Labels: refactor
