Repository emdgroup/baybe, pull requests merged in 2024-03, with the labels that each got.

#158 HOTFIX: Downgrade upload-pages-artifact action to v1
  .github/workflows/docs.yml
Labels: bug, repo

#152 Feature/pretty print campaign
  CHANGELOG.md
  baybe/campaign.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
Labels: enhancement

#157 Chemical Encoding Docs Update
  CHANGELOG.md
  README.md
  docs/index.md
  docs/misc/readme_link.md
  docs/scripts/convert_code_to_documentation.py
  docs/scripts/utils.py
  docs/userguide/parameters.md
  examples/Backtesting/full_lookup.py
  examples/Backtesting/full_lookup_dark.svg
  examples/Backtesting/full_lookup_light.svg
Labels: documentation

#140 First draft of Transfer Learning User Guide
  CHANGELOG.md
  docs/userguide/transfer_learning.md
Labels: documentation

#159 Extend `from_simplex` with constraints
  CHANGELOG.md
  baybe/searchspace/discrete.py
  examples/Constraints_Discrete/mixture_constraints.py
Labels: bug, new feature

#167 Fix Regular Action
  .github/workflows/regular.yml
Labels: bug

#166 Add efficient `from_simplex` validation
  CHANGELOG.md
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  tests/conftest.py
  tests/serialization/test_campaign_serialization.py
Labels: enhancement

#170 New search space userguide
  CHANGELOG.md
  baybe/searchspace/discrete.py
  docs/userguide/searchspace.md
Labels: documentation

#172 Simulation userguide
  CHANGELOG.md
  docs/userguide/simulation.md
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/backtesting_dark.svg
  examples/Transfer_Learning/backtesting_light.svg
Labels: documentation

#153 Enable Python 3.12
  .github/workflows/ci.yml
  .github/workflows/regular.yml
  .github/workflows/release.yml
  CHANGELOG.md
  CONTRIBUTING.md
  baybe/campaign.py
  docs/userguide/transfer_learning.md
  pyproject.toml
  tests/README.md
  tox.ini
Labels: enhancement

#176 Python syntax upgrade
  .pre-commit-config.yaml
  CHANGELOG.md
  baybe/acquisition.py
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/constraints/validation.py
  baybe/objective.py
  baybe/parameters/categorical.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/parameters/utils.py
  baybe/parameters/validation.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/scaler.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/searchspace/validation.py
  baybe/serialization/core.py
  baybe/serialization/mixin.py
  baybe/simulation.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  baybe/targets/numerical.py
  baybe/telemetry.py
  baybe/utils/basic.py
  baybe/utils/chemistry.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
  baybe/utils/numerical.py
  baybe/utils/plotting.py
  baybe/utils/sampling_algorithms.py
  docs/scripts/utils.py
  examples/Backtesting/multi_target.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/basic_transfer_learning.py
  tests/conftest.py
  tests/docs/utils.py
  tests/serialization/test_meta_recommender_serialization.py
  tests/test_custom_surrogate.py
  tests/test_deprecations.py
Labels: repo

#175 Feature/pretty print objective
  CHANGELOG.md
  baybe/objective.py
  baybe/parameters/base.py
  baybe/searchspace/core.py
  baybe/targets/base.py
  baybe/targets/numerical.py
Labels: enhancement

#174 Enable flexible dataframe de-serialization
  CHANGELOG.md
  baybe/serialization/core.py
  tests/serialization/test_dataframe_serialization.py
Labels: new feature

#180 Change order in sidebar
  docs/index.md
Labels: bug, documentation

#181 Remove optional telemetry group
  CHANGELOG.md
  pyproject.toml
Labels: bug, repo

#185 Fix ONNX vulnerability
  CHANGELOG.md
  pyproject.toml
  tox.ini
Labels: repo

#183 Botorch settings
  CHANGELOG.md
  baybe/recommenders/pure/bayesian/base.py
  baybe/surrogates/gaussian_process.py
Labels: enhancement

#186 Release 0.8.2
  CHANGELOG.md
Labels: repo
