Repository emdgroup/baybe, pull requests merged in 2024-05, with the labels that each got.

#216 Serialization user guide
  CHANGELOG.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/exceptions.py
  baybe/objectives/base.py
  baybe/objectives/deprecation.py
  baybe/serialization/core.py
  baybe/utils/basic.py
  docs/userguide/campaigns.md
  docs/userguide/serialization.md
  docs/userguide/userguide.md
  tests/docs/utils.py
  tests/hypothesis_strategies/alternative_creation/test_acquisition.py
  tests/serialization/test_deserialization.py
  tests/test_iterations.py
Labels: documentation

#209 Refactor surrogates and decorators
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/surrogates/__init__.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  docs/conf.py
  docs/userguide/surrogates.md
  examples/Basics/recommenders.py
  streamlit/surrogate_models.py
  tests/serialization/test_surrogate_serialization.py
  tests/test_iterations.py
Labels: refactor

#224 Simplification of doc building script
  .github/workflows/docs.yml
  docs/conf.py
  docs/scripts/convert_code_to_documentation.py
Labels: documentation

#225 More Priors
  CHANGELOG.md
  baybe/kernels/priors/__init__.py
  baybe/kernels/priors/basic.py
  baybe/utils/validation.py
  tests/conftest.py
  tests/hypothesis_strategies/basic.py
  tests/hypothesis_strategies/priors.py
  tests/hypothesis_strategies/utils.py
  tests/test_iterations.py
Labels: new feature

#237 Fix telemetry execution
  CHANGELOG.md
  baybe/telemetry.py
  tests/simulate_telemetry.py
Labels: bug

#213 Enable returning incomplete simulation results
  CHANGELOG.md
  baybe/simulation/core.py
Labels: new feature

#221 Include custom `ScaleKernel`
  CHANGELOG.md
  baybe/kernels/__init__.py
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/surrogates/gaussian_process.py
  baybe/utils/basic.py
  baybe/utils/conversion.py
  tests/hypothesis_strategies/kernels.py
  tests/serialization/test_kernel_serialization.py
  tests/test_iterations.py
Labels: enhancement

#235 Refactor GP Surrogates
  CHANGELOG.md
  baybe/kernels/base.py
  baybe/surrogates/__init__.py
  baybe/surrogates/gaussian_process/__init__.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/gaussian_process/kernel_factory.py
  baybe/surrogates/gaussian_process/presets/__init__.py
  baybe/surrogates/gaussian_process/presets/core.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/utils/boolean.py
  docs/userguide/surrogates.md
  pyproject.toml
  tests/conftest.py
Labels: enhancement, refactor

#240 Ditch `requests`
  CHANGELOG.md
  baybe/telemetry.py
  pyproject.toml
Labels: enhancement

#245 Increate hypothesis deadline
  tests/conftest.py
Labels: enhancement, repo

#239 Avoid altering RNG states
  CHANGELOG.md
  baybe/simulation/core.py
  baybe/simulation/scenarios.py
  baybe/utils/basic.py
  baybe/utils/random.py
Labels: enhancement

#227 User guide for environment variables
  CHANGELOG.md
  README.md
  baybe/telemetry.py
  docs/userguide/envvars.md
  docs/userguide/userguide.md
Labels: documentation

#242 Minor README fixes
  CONTRIBUTORS.md
  README.md
Labels: documentation

#228 Memory estimation utilities
  CHANGELOG.md
  baybe/constraints/validation.py
  baybe/parameters/base.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/utils/dataframe.py
  baybe/utils/memory.py
  tests/test_utils.py
Labels: new feature

#244 Add more kernels
  CHANGELOG.md
  baybe/kernels/__init__.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/priors/__init__.py
  tests/hypothesis_strategies/kernels.py
  tests/test_iterations.py
Labels: new feature

#217 Release 0.9.0
  CHANGELOG.md
  README.md
  baybe/__init__.py
  baybe/deprecation.py
  baybe/strategies/__init__.py
  baybe/strategies/deprecation.py
  baybe/surrogate.py
  baybe/targets/__init__.py
  baybe/targets/deprecation.py
  baybe/telemetry.py
  docs/templates/custom-module-template.rst
  docs/userguide/campaigns.md
  docs/userguide/objectives.md
  docs/userguide/targets.md
  docs/userguide/userguide.md
  examples/Multi_Target/Multi_Target_Header.md
  mypy.ini
  tests/test_deprecations.py
Labels: repo, release

#248 Fix wrong picture in README
  docs/scripts/convert_code_to_documentation.py
  docs/scripts/utils.py
Labels: documentation

#251 Fix surrogate slots
  CHANGELOG.md
  baybe/surrogates/base.py
Labels: bug

#234 Separate tox commands for doc building
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/regular.yml
  docs/conf.py
  docs/scripts/build_documentation.py
  docs/scripts/build_examples.py
  docs/scripts/check_links.py
  docs/scripts/convert_code_to_documentation.py
  docs/scripts/utils.py
  tox.ini
Labels: documentation
