Repository emdgroup/baybe, pull requests merged in 2024-11, with the labels that each got.

#418 Add downloads badge
  README.md
Labels: documentation

#421 Unpin protobuf
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  pyproject.toml
Labels: bug

#422 Fix Asserts in Dependency Constraint Example
  examples/Constraints_Discrete/dependency_constraints.py
Labels: documentation

#394 Rework Mixture Examples
  CHANGELOG.md
  docs/userguide/constraints.md
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Mixtures/Mixtures_Header.md
  examples/Mixtures/slot_based.py
  examples/Mixtures/traditional.py
Labels: documentation, enhancement

#417 Use correct precision in botorch wrapper
  baybe/utils/botorch_wrapper.py
Labels: bug

#364 Enable scikit-fingerprints
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  baybe/_optional/chem.py
  baybe/_optional/info.py
  baybe/parameters/enum.py
  baybe/parameters/substance.py
  baybe/searchspace/core.py
  baybe/surrogates/gaussian_process/presets/edbo.py
  baybe/utils/chemistry.py
  docs/conf.py
  docs/userguide/parameters.md
  examples/Backtesting/full_lookup.py
  examples/Backtesting/full_lookup_dark.svg
  examples/Backtesting/full_lookup_light.svg
  mypy.ini
  pyproject.toml
  tests/hypothesis_strategies/parameters.py
  tests/test_deprecations.py
  tests/test_fingerprints.py
Labels: enhancement, new feature

#399 Fix rare degenerate `comp_df` bug
  CHANGELOG.md
  baybe/parameters/custom.py
  baybe/parameters/substance.py
  baybe/utils/dataframe.py
  tests/test_custom_parameter.py
  tests/test_substance_parameter.py
  tests/utils/test_dataframe.py
  tests/validation/test_parameter_validation.py
Labels: bug

#413 Basic benchmarking structure
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  baybe/serialization/core.py
  benchmarks/__init__.py
  benchmarks/__main__.py
  benchmarks/definition/__init__.py
  benchmarks/definition/config.py
  benchmarks/domains/__init__.py
  benchmarks/domains/synthetic_2C1D_1C.py
  benchmarks/result/__init__.py
  benchmarks/result/metadata.py
  benchmarks/result/result.py
  mypy.ini
  pyproject.toml
Labels: new feature

#427 Require truthy/falsy values for `BAYBE_DEACTIVATE_POLARS`
  CHANGELOG.md
  baybe/searchspace/discrete.py
  docs/userguide/envvars.md
Labels: enhancement

#415 Fix dtype in continuous comp rep
  CHANGELOG.md
  baybe/searchspace/continuous.py
  docs/userguide/envvars.md
Labels: bug, enhancement

#434 Drop CI audit dependence
  .github/workflows/ci.yml
Labels: repo

#412 Immutable searchspace
  CHANGELOG.md
  README.md
  baybe/acquisition/base.py
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/kernels/base.py
  baybe/objectives/base.py
  baybe/objectives/desirability.py
  baybe/priors/base.py
  baybe/recommenders/pure/base.py
  baybe/searchspace/_annotated.py
  baybe/searchspace/continuous.py
  baybe/searchspace/discrete.py
  baybe/serialization/core.py
  baybe/simulation/core.py
  baybe/simulation/scenarios.py
  baybe/simulation/transfer_learning.py
  baybe/surrogates/gaussian_process/kernel_factory.py
  baybe/utils/basic.py
  baybe/utils/dataframe.py
  docs/userguide/campaigns.md
  docs/userguide/constraints.md
  docs/userguide/recommenders.md
  docs/userguide/searchspace.md
  docs/userguide/serialization.md
  examples/Serialization/Serialization_Header.md
  tests/test_campaign.py
  tests/test_deprecations.py
Labels: refactor

#429 Add manual benchmark workflow and S3 result persistence
  .github/workflows/manual_benchmark.yml
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  CONTRIBUTORS.md
  benchmarks/README.md
  benchmarks/__main__.py
  benchmarks/definition/config.py
  benchmarks/persistence/__init__.py
  benchmarks/persistence/persistence.py
  benchmarks/result/metadata.py
  benchmarks/result/result.py
  benchmarks/serialization.py
  mypy.ini
  pyproject.toml
Labels: new feature, benchmarking
