Repository emdgroup/baybe, pull requests merged in 2024-06, with the labels that each got.

#254 Fix dtypes related to floating point precision
  CHANGELOG.md
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/objectives/desirability.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/simulation/core.py
  baybe/simulation/lookup.py
  baybe/utils/chemistry.py
  baybe/utils/memory.py
  tests/conftest.py
  tests/hypothesis_strategies/acquisition.py
  tests/hypothesis_strategies/basic.py
  tests/hypothesis_strategies/constraints.py
  tests/hypothesis_strategies/dataframes.py
  tests/hypothesis_strategies/objectives.py
  tests/hypothesis_strategies/parameters.py
  tests/test_searchspace.py
  tests/validation/test_objective_validation.py
  tests/validation/test_parameter_validation.py
  tox.ini
Labels: bug

#258 Release 0.9.1
  CHANGELOG.md
Labels: release

#253 Drop Python 3.9
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/regular.yml
  CHANGELOG.md
  baybe/utils/interval.py
  pyproject.toml
  tests/README.md
  tox.ini
Labels: repo

#220 Refactor recommender signature
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/base.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/simulation/core.py
  examples/Multi_Target/desirability.py
  mypy.ini
  tests/conftest.py
  tests/serialization/test_campaign_serialization.py
  tests/test_deprecations.py
  tests/test_integration.py
Labels: refactor

#255 Python 3.10 syntax upgrade
  .pre-commit-config.yaml
  baybe/acquisition/_adapter.py
  baybe/acquisition/base.py
  baybe/acquisition/partial.py
  baybe/acquisition/utils.py
  baybe/campaign.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/objective.py
  baybe/objectives/base.py
  baybe/objectives/desirability.py
  baybe/parameters/base.py
  baybe/parameters/custom.py
  baybe/parameters/substance.py
  baybe/parameters/utils.py
  baybe/recommenders/base.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/scaler.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/serialization/core.py
  baybe/simulation/core.py
  baybe/simulation/lookup.py
  baybe/simulation/scenarios.py
  baybe/simulation/transfer_learning.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/kernel_factory.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  baybe/surrogates/validation.py
  baybe/targets/numerical.py
  baybe/telemetry.py
  baybe/utils/basic.py
  baybe/utils/chemistry.py
  baybe/utils/conversion.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
  baybe/utils/validation.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  tests/conftest.py
  tests/docs/utils.py
  tests/hypothesis_strategies/constraints.py
  tests/hypothesis_strategies/parameters.py
  tests/hypothesis_strategies/targets.py
Labels: repo

#261 Fix changelog
  CHANGELOG.md
Labels: bug

#260 Refactor adapter model
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/surrogates/_adapter.py
  baybe/surrogates/base.py
  baybe/surrogates/gaussian_process/core.py
  tests/test_imports.py
Labels: refactor

#256 Deprecate SequentialGreedyRecommender
  CHANGELOG.md
  README.md
  baybe/recommenders/__init__.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/__init__.py
  baybe/recommenders/pure/bayesian/__init__.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/bayesian/sequential_greedy.py
  baybe/searchspace/continuous.py
  baybe/searchspace/discrete.py
  docs/templates/custom-module-template.rst
  docs/userguide/campaigns.md
  docs/userguide/recommenders.md
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/hybrid.py
  examples/Basics/recommenders.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Searchspaces/hybrid_space.py
  examples/Serialization/basic_serialization.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  tests/conftest.py
  tests/hypothesis_strategies/alternative_creation/test_acquisition.py
  tests/serialization/test_naive_hybrid_serialization.py
  tests/simulate_telemetry.py
  tests/test_acquisition.py
  tests/test_deprecations.py
  tests/test_iterations.py
  tests/test_meta_recommenders.py
Labels: enhancement

#262 Campaign validators
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/base.py
  tests/conftest.py
  tests/test_deprecations.py
Labels: enhancement

#271 Add upper version limits
  CHANGELOG.md
  baybe/utils/chemistry.py
  pyproject.toml
Labels: repo

#272 Fix optional dependency flags
  baybe/_optional/info.py
  pyproject.toml
  tox.ini
Labels: bug

#243 Cardinality constraints for random recommender
  CHANGELOG.md
  CONTRIBUTORS.md
  baybe/constraints/__init__.py
  baybe/constraints/base.py
  baybe/constraints/continuous.py
  baybe/constraints/validation.py
  baybe/parameters/numerical.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/targets/numerical.py
  baybe/utils/interval.py
  tests/test_cardinality_constraint.py
  tests/test_deprecations.py
  tests/test_searchspace.py
  tests/validation/test_constraint_validation.py
  tests/validation/test_interval_validation.py
  tests/validation/test_parameter_validation.py
  tests/validation/test_target_validation.py
Labels: new feature

#276 `register_hooks` utility
  CHANGELOG.md
  baybe/utils/__init__.py
  baybe/utils/basic.py
  examples/Custom_Hooks/Custom_Hooks_Header.md
  examples/Custom_Hooks/basics.py
  tests/test_utils.py
Labels: enhancement, new feature

#277 Remove core test caching
  .github/workflows/ci.yml
  .github/workflows/regular.yml
Labels: repo

#282 Fix attrs incompatibility of pydoclint
  .pre-commit-config.yaml
  pydoclint.toml
  pyproject.toml
Labels: repo

#281 Replace `is_numeric` class attribute with `is_numerical`
  CHANGELOG.md
  baybe/campaign.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/utils/dataframe.py
Labels: refactor

#270 Add discrete cardinality constraint
  CHANGELOG.md
  baybe/constraints/__init__.py
  baybe/constraints/base.py
  baybe/constraints/continuous.py
  baybe/constraints/discrete.py
  baybe/constraints/validation.py
  baybe/searchspace/continuous.py
  baybe/searchspace/discrete.py
  tests/conftest.py
  tests/constraints/__init__.py
  tests/constraints/test_cardinality_constraint_continuous.py
  tests/constraints/test_cardinality_constraint_discrete.py
  tests/constraints/test_constraints_continuous.py
  tests/constraints/test_constraints_discrete.py
  tests/test_cardinality_constraint.py
  tests/test_searchspace.py
Labels: new feature
