Repository emdgroup/baybe, pull requests merged in 2024-10, with the labels that each got.

#384 Consolidate Continuous Linear Constraints
  CHANGELOG.md
  baybe/constraints/__init__.py
  baybe/constraints/base.py
  baybe/constraints/continuous.py
  baybe/constraints/deprecation.py
  baybe/searchspace/continuous.py
  docs/userguide/constraints.md
  examples/Backtesting/multi_target.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  tests/conftest.py
  tests/constraints/test_cardinality_constraint_continuous.py
  tests/constraints/test_constraints_continuous.py
  tests/hypothesis_strategies/constraints.py
  tests/serialization/test_constraint_serialization.py
  tests/test_deprecations.py
  tests/test_searchspace.py
Labels: enhancement

#388 Release 0.11.1
  CHANGELOG.md
Labels: release

#397 Subclass garbage collection
  CHANGELOG.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/acquisition/partial.py
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/continuous.py
  baybe/constraints/discrete.py
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/objectives/base.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/priors/base.py
  baybe/priors/basic.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/bandit.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/gaussian_process/kernel_factory.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/surrogates/gaussian_process/presets/edbo.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/targets/base.py
  baybe/targets/binary.py
  baybe/targets/numerical.py
  baybe/utils/interval.py
  baybe/utils/scaling.py
Labels: bug

#390 Update known_issues.md
  CHANGELOG.md
  docs/known_issues.md
Labels: documentation

#395 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#389 Add Continuous Optimization Controls to BotorchRecommender
  CHANGELOG.md
  baybe/recommenders/pure/bayesian/botorch.py
  docs/userguide/recommenders.md
Labels: enhancement

#392 Add Explanation of some Utilities to User Guide
  CHANGELOG.md
  baybe/simulation/lookup.py
  baybe/utils/dataframe.py
  docs/userguide/async.md
  docs/userguide/userguide.md
  docs/userguide/utils.md
  examples/Basics/campaign.py
  examples/Basics/recommenders.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/desirability.py
  tests/conftest.py
  tests/docs/test_docs.py
  tests/simulate_telemetry.py
  tests/test_input_output.py
  tests/test_pending_experiments.py
  tests/test_surrogate.py
Labels: documentation

#401 Release 0.11.2
  CHANGELOG.md
  docs/userguide/utils.md
Labels: release

#405 Fix math in CardinalityConstraint docstring
  baybe/constraints/base.py
Labels: documentation

#400 Typing overrides
  CHANGELOG.md
  CONTRIBUTING.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/partial.py
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/objectives/base.py
  baybe/objectives/deprecation.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/priors/basic.py
  baybe/recommenders/base.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/_adapter.py
  baybe/surrogates/bandit.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/gaussian_process/kernel_factory.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/surrogates/gaussian_process/presets/edbo.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/targets/base.py
  baybe/targets/binary.py
  baybe/targets/numerical.py
  baybe/utils/basic.py
  mypy.ini
  tests/validation/test_acqf_validation.py
Labels: typing

#407 Bump Streamlit Requirement
  .lockfiles/py310-dev.lock
  pyproject.toml
Labels: bug

#398 Refactor objective transform interface
  CHANGELOG.md
  baybe/objectives/base.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/searchspace/validation.py
  baybe/surrogates/base.py
  baybe/utils/dataframe.py
  baybe/utils/validation.py
  examples/Multi_Target/desirability.py
  tests/test_deprecations.py
  tests/validation/test_searchspace_validation.py
Labels: enhancement, refactor

#404 Add Polars installation issues to known_issues
  docs/known_issues.md
Labels: documentation

#406 Refactor target transform interface
  .lockfiles/py310-dev.lock
  .pre-commit-config.yaml
  CHANGELOG.md
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/parameters/base.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/targets/base.py
  baybe/targets/binary.py
  baybe/targets/numerical.py
  pyproject.toml
  tests/test_deprecations.py
Labels: refactor

#411 Drop `batch_quantity` keyword
  baybe/campaign.py
Labels: bug
