Repository emdgroup/baybe, pull requests merged in 2024-07, with the labels that each got.

#293 Remove tox caching in Regular
  .github/workflows/regular.yml
Labels: repo

#298 Fix serialization and caching
  .github/workflows/ci.yml
  .github/workflows/regular.yml
  CHANGELOG.md
  baybe/recommenders/pure/nonpredictive/clustering.py
Labels: bug, refactor

#289 Refactor search space `transform` methods
  CHANGELOG.md
  baybe/parameters/base.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/searchspace/validation.py
  tests/test_deprecations.py
  tests/validation/test_searchspace_validation.py
Labels: new feature, refactor

#278 Comp Rep Transition Point
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/exceptions.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/surrogates/base.py
  baybe/surrogates/utils.py
Labels: refactor

#292 Fix MetaRecommender Warnings
  CHANGELOG.md
  baybe/exceptions.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/pure/nonpredictive/base.py
  tests/test_iterations.py
Labels: enhancement

#302 Fix Deprecated Calls
  baybe/acquisition/acqfs.py
  baybe/recommenders/pure/bayesian/base.py
Labels: deprecation

#252 Polars pipeline for discrete sum, product and exclusion constraints
  CHANGELOG.md
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/searchspace/discrete.py
  docs/conf.py
  mypy.ini
  pyproject.toml
  tests/test_constraints_polars.py
Labels: enhancement

#299 Update TL User Guide
  CHANGELOG.md
  docs/conf.py
  docs/references.bib
  docs/userguide/transfer_learning.md
  pyproject.toml
Labels: documentation

#265 Reorganize simulation lookup
  CHANGELOG.md
  baybe/simulation/_imputation.py
  baybe/simulation/core.py
  baybe/simulation/lookup.py
  baybe/utils/basic.py
  baybe/utils/dataframe.py
  examples/Basics/campaign.py
  examples/Basics/recommenders.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/desirability.py
  pytest.ini
  tests/conftest.py
  tests/simulate_telemetry.py
  tests/test_input_output.py
Labels: refactor

#288 Change path from sys.path[0] to .
  CHANGELOG.md
  baybe/utils/plotting.py
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/full_lookup.py
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/basic_transfer_learning.py
Labels: documentation

#303 Searchspace convenience constructors
  CHANGELOG.md
  baybe/campaign.py
  baybe/parameters/base.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
Labels: new feature

#308 Add KnowledgeGradient ACQF
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  pyproject.toml
  tests/hypothesis_strategies/acquisition.py
  tests/test_iterations.py
  tox.ini
Labels: new feature

#309 Surrogate Posteriors
  CHANGELOG.md
  baybe/surrogates/_adapter.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
Labels: refactor

#290 Augmentation Utilities
  CHANGELOG.md
  baybe/constraints/base.py
  baybe/constraints/discrete.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/utils/augmentation.py
  tests/test_utils.py
  tests/utils/test_augmentation.py
  tests/utils/test_basic.py
  tests/utils/test_memory.py
  tests/utils/test_numerical.py
  tests/utils/test_sampling_algorithms.py
Labels: new feature

#311 Fix kernel translation
  CHANGELOG.md
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/exceptions.py
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/priors/base.py
  baybe/utils/basic.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  ruff.toml
  tests/hypothesis_strategies/basic.py
  tests/hypothesis_strategies/kernels.py
  tests/test_kernels.py
  tests/validation/kernels/__init__.py
  tests/validation/kernels/test_basic_kernel_validation.py
  tests/validation/kernels/test_composite_kernel_validation.py
Labels: bug, enhancement

#316 Upgrade dev tools
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  baybe/acquisition/partial.py
  baybe/constraints/validation.py
  baybe/kernels/basic.py
  baybe/kernels/composite.py
  baybe/parameters/substance.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/searchspace/discrete.py
  baybe/serialization/core.py
  baybe/simulation/transfer_learning.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/linear.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  baybe/utils/dataframe.py
  baybe/utils/sampling_algorithms.py
  baybe/utils/torch.py
  docs/scripts/build_documentation.py
  pyproject.toml
  ruff.toml
  tests/constraints/test_constraints_continuous.py
  tests/constraints/test_constraints_discrete.py
  tests/hypothesis_strategies/parameters.py
  tests/hypothesis_strategies/targets.py
  tests/test_continuous.py
  tests/test_custom_surrogate.py
  tests/test_input_output.py
  tests/test_streamlit.py
  tests/utils/test_augmentation.py
  tests/utils/test_memory.py
  tests/utils/test_numerical.py
  tests/utils/test_sampling_algorithms.py
  tests/validation/kernels/test_basic_kernel_validation.py
  tests/validation/kernels/test_composite_kernel_validation.py
  tests/validation/test_objective_validation.py
Labels: repo

#306 Polars: from_product() implementation
  CHANGELOG.md
  CONTRIBUTORS.md
  baybe/searchspace/discrete.py
  pyproject.toml
  tests/test_constraints_polars.py
Labels: enhancement

#273 Add Active Learning Userguide
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  docs/userguide/active_learning.md
  docs/userguide/userguide.md
  tests/hypothesis_strategies/acquisition.py
Labels: documentation

#313 Ignore `UnusedObjectWarning` caused by nonpred recommenders in simulation
  CHANGELOG.md
  baybe/simulation/scenarios.py
Labels: enhancement

#310 Temp Fix: Avoid Prior Jumps
  CHANGELOG.md
  baybe/surrogates/gaussian_process/presets/__init__.py
  baybe/surrogates/gaussian_process/presets/default.py
  baybe/surrogates/gaussian_process/presets/edbo.py
  docs/conf.py
  tests/test_iterations.py
Labels: bug

#320 Restore old MLL fit
  CHANGELOG.md
  baybe/surrogates/gaussian_process/core.py
Labels: bug

#315 Surrogate scaling
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/parameters/base.py
  baybe/parameters/numerical.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/scaler.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  baybe/utils/dataframe.py
  baybe/utils/scaling.py
  examples/Custom_Surrogates/Custom_Surrogates_Header.md
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  mypy.ini
  ruff.toml
  streamlit/initial_recommender.py
  streamlit/surrogate_models.py
  tests/test_continuous.py
  tests/test_custom_surrogate.py
  tests/test_deprecations.py
  tests/test_searchspace.py
Labels: enhancement, refactor

#324 Fix broken docstring links
  baybe/surrogates/gaussian_process/presets/default.py
Labels: documentation

#326 Switch to log-acqfs
  CHANGELOG.md
  baybe/recommenders/pure/bayesian/base.py
Labels: enhancement

#318 Make Polars Optional
  README.md
  baybe/_optional/info.py
  baybe/_optional/polars.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/searchspace/discrete.py
  docs/userguide/envvars.md
  pyproject.toml
  tests/test_constraints_polars.py
  tox.ini
Labels: enhancement
