Repository emdgroup/baybe, pull requests merged in 2024-09, with the labels that each got.

#348 Fix batch recommendation
  CHANGELOG.md
  baybe/exceptions.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  streamlit/surrogate_models.py
  tests/test_iterations.py
Labels: bug

#361 Remove token from publishing pipelines
  .github/workflows/release.yml
Labels: repo

#341 Parameter permutation
  CHANGELOG.md
  baybe/parameters/categorical.py
  baybe/parameters/substance.py
  baybe/parameters/utils.py
  baybe/searchspace/continuous.py
  baybe/searchspace/discrete.py
  examples/Custom_Hooks/campaign_stopping.py
  tests/test_searchspace.py
Labels: bug

#362 Add workflow permissions
  .github/workflows/release.yml
Labels: repo

#350 Best_f from posterior means
  CHANGELOG.md
  baybe/acquisition/base.py
Labels: refactor

#360 Fix `SubspaceDiscrete.from_dataframe` edge case
  CHANGELOG.md
  baybe/campaign.py
  baybe/searchspace/discrete.py
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
Labels: bug

#343 Multi-Armed Bandit
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/exceptions.py
  baybe/parameters/base.py
  baybe/priors/__init__.py
  baybe/priors/basic.py
  baybe/recommenders/base.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/serialization/core.py
  baybe/surrogates/__init__.py
  baybe/surrogates/bandit.py
  baybe/targets/__init__.py
  baybe/targets/binary.py
  baybe/utils/dataframe.py
  baybe/utils/validation.py
  examples/Multi_Armed_Bandit/Multi_Armed_Bandit_Header.md
  examples/Multi_Armed_Bandit/bernoulli_multi_armed_bandit.py
  tests/conftest.py
  tests/hypothesis_strategies/kernels.py
  tests/hypothesis_strategies/priors.py
  tests/hypothesis_strategies/targets.py
  tests/serialization/test_prior_serialization.py
  tests/serialization/test_target_serialization.py
  tests/test_iterations.py
  tests/validation/test_target_validation.py
Labels: new feature

#347 Fix visuals in examples
  baybe/campaign.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/parameters/numerical.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/bandit.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/linear.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/utils/dataframe.py
  baybe/utils/plotting.py
  examples/Basics/recommenders.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Serialization/basic_serialization.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
Labels: documentation

#319 Enable Pending Points
  CHANGELOG.md
  README.md
  baybe/acquisition/base.py
  baybe/campaign.py
  baybe/exceptions.py
  baybe/recommenders/base.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  docs/userguide/async.md
  docs/userguide/recommenders.md
  docs/userguide/searchspace.md
  docs/userguide/userguide.md
  tests/conftest.py
  tests/docs/test_docs.py
  tests/test_pending_experiments.py
Labels: new feature

#370 Fix Recommendation Order for BotorchRecommender
  CHANGELOG.md
  baybe/recommenders/pure/bayesian/botorch.py
  tests/test_input_output.py
Labels: bug

#355 Expose surrogate
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/base.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/serialization/core.py
  baybe/serialization/mixin.py
  baybe/surrogates/base.py
  mypy.ini
  pyproject.toml
  tests/test_deprecations.py
  tests/test_surrogate.py
Labels: new feature

#317 Multi-version documentation
  .github/workflows/docs.yml
  CHANGELOG.md
  docs/conf.py
  docs/index.md
  docs/scripts/utils.py
Labels: documentation, enhancement, new feature, repo, release

#377 Fix broken links to stable
  README.md
  baybe/telemetry.py
Labels: bug, documentation

#376 Release 0.11.0
  CHANGELOG.md
Labels: release

#380 Speedup Bernoulli Multi-Armed Bandit Example
  examples/Multi_Armed_Bandit/bernoulli_multi_armed_bandit.py
Labels: enhancement

#382 Fix intersphinx link for torch
  docs/conf.py
Labels: documentation

#379 Fix Name Matching for Retrieving Comp Rep Indices
  CHANGELOG.md
  baybe/searchspace/core.py
Labels: bug

#386 Remove `get_surrogate` Restrictions
  CHANGELOG.md
  baybe/campaign.py
  docs/userguide/surrogates.md
  tests/test_campaign.py
Labels: enhancement
