Repository emdgroup/baybe, pull requests merged in 2024-02, with the labels that each got.

#105 Move doc building utilities to separate file
  docs/scripts/convert_code_to_documentation.py
  docs/scripts/utils.py
Labels: documentation

#108 Fix dataframe hypothesis strategy
  tests/hypothesis_strategies/dataframes.py
  tests/serialization/test_dataframe_serialization.py
Labels: enhancement, tests

#106 Refactor exposed campaign attributes
  CHANGELOG.md
  baybe/campaign.py
  baybe/exceptions.py
  docs/userguide/campaigns.md
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Multi_Target/desirability.py
  tests/test_constraints_continuous.py
  tests/test_deprecations.py
Labels: enhancement

#107 Rename batch_quantity to batch_size
  CHANGELOG.md
  README.md
  baybe/campaign.py
  baybe/recommenders/base.py
  baybe/recommenders/bayesian.py
  baybe/recommenders/clustering.py
  baybe/recommenders/sampling.py
  baybe/simulation.py
  baybe/strategies/base.py
  baybe/strategies/composite.py
  baybe/telemetry.py
  docs/userguide/campaigns.md
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/hybrid.py
  examples/Backtesting/impute_mode.py
  examples/Backtesting/multi_target.py
  examples/Basics/campaign.py
  examples/Basics/strategies.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/desirability.py
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Searchspaces/continuous_space_custom_function.py
  examples/Searchspaces/discrete_space.py
  examples/Searchspaces/hybrid_space.py
  examples/Serialization/basic_serialization.py
  examples/Serialization/create_from_config.py
  streamlit/initial_strategy.py
  tests/conftest.py
  tests/test_constraints_continuous.py
  tests/test_custom_parameter.py
  tests/test_custom_surrogate.py
  tests/test_deprecations.py
  tests/test_input_output.py
  tests/test_iterations.py
  tests/test_substance_parameter.py
Labels: enhancement

#99 Explicit top-level files for example folders
  CHANGELOG.md
  docs/conf.py
  docs/misc/license_link.md
  docs/scripts/utils.py
  examples/Backtesting/Backtesting_Header.md
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/hybrid.py
  examples/Backtesting/impute_mode.py
  examples/Backtesting/multi_target.py
  examples/Basics/Basics_Header.md
  examples/Basics/campaign.py
  examples/Basics/strategies.py
  examples/Constraints_Continuous/Constraints_Continuous_Header.md
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Constraints_Discrete/Constraints_Discrete_Header.md
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/Custom_Surrogates_Header.md
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/Multi_Target_Header.md
  examples/Multi_Target/desirability.py
  examples/Searchspaces/Searchspaces_Header.md
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Searchspaces/continuous_space_custom_function.py
  examples/Searchspaces/discrete_space.py
  examples/Searchspaces/hybrid_space.py
  examples/Serialization/Serialization_Header.md
  examples/Serialization/basic_serialization.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
Labels: documentation

#109 Fix example output in documentation
  docs/scripts/utils.py
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/hybrid.py
  examples/Backtesting/impute_mode.py
  examples/Backtesting/multi_target.py
  examples/Basics/strategies.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Searchspaces/continuous_space_custom_function.py
  examples/Searchspaces/discrete_space.py
  examples/Searchspaces/hybrid_space.py
  examples/Serialization/basic_serialization.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
Labels: documentation

#110 Recommender Protocol and Related Signature Changes
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/base.py
  baybe/recommenders/bayesian.py
  baybe/recommenders/clustering.py
  baybe/recommenders/deprecation.py
  baybe/recommenders/sampling.py
  baybe/serialization/core.py
  baybe/simulation.py
  baybe/strategies/base.py
  baybe/strategies/deprecation.py
  examples/Basics/strategies.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  tests/conftest.py
  tests/docs/test_docs.py
  tests/simulate_telemetry.py
  tests/test_deprecations.py
Labels: enhancement

#112 Small import optimizations
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/regular.yml
  .github/workflows/release.yml
  CHANGELOG.md
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/discrete.py
  baybe/objective.py
  baybe/parameters/custom.py
  baybe/parameters/numerical.py
  baybe/parameters/substance.py
  baybe/recommenders/bayesian.py
  baybe/recommenders/deprecation.py
  baybe/recommenders/sampling.py
  baybe/scaler.py
  baybe/searchspace/continuous.py
  baybe/searchspace/discrete.py
  baybe/serialization/core.py
  baybe/simulation.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/targets/numerical.py
  baybe/telemetry.py
  baybe/utils/__init__.py
  baybe/utils/basic.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
  baybe/utils/numerical.py
  examples/Basics/campaign.py
  examples/Basics/strategies.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/desirability.py
  tests/conftest.py
  tests/hypothesis_strategies/parameters.py
  tests/serialization/test_naive_hybrid_serialization.py
Labels: enhancement

#113 Update project metadata
  README.md
  docs/conf.py
Labels: repo

#115 Hotfix: Disappearing Task Parameters
  CHANGELOG.md
  baybe/searchspace/discrete.py
Labels: bug

#116 Fix coretest
  .gitignore
  CHANGELOG.md
  tests/conftest.py
  tests/docs/test_docs.py
  tests/hypothesis_strategies/alternative_creation/test_parameters.py
  tests/hypothesis_strategies/parameters.py
  tests/serialization/test_parameter_serialization.py
  tests/test_custom_surrogate.py
  tests/test_streamlit.py
  tests/test_substance_parameter.py
  tests/validation/test_parameter_validation.py
  tox.ini
Labels: bug

#122 Remove `SubstanceParameter` from basic serialization example
  CHANGELOG.md
  examples/Serialization/basic_serialization.py
Labels: bug

#117 `SubspaceDiscrete.from_simplex` convenience constructor
  CHANGELOG.md
  baybe/searchspace/discrete.py
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
  tests/hypothesis_strategies/parameters.py
  tests/serialization/test_searchspace_serialization.py
Labels: new feature

#126 Fix docs pipeline
  .github/workflows/docs.yml
Labels: repo

#127 Change docs pipeline python version to 3.9
  .github/workflows/docs.yml
  README.md
Labels: repo

#129 Refactor recommender methods
  CHANGELOG.md
  baybe/recommenders/base.py
  baybe/recommenders/bayesian/base.py
  baybe/recommenders/bayesian/sequential_greedy.py
  baybe/recommenders/nonpredictive/base.py
  baybe/recommenders/nonpredictive/sampling.py
Labels: enhancement, repo

#111 Multi-version plotting & SMOKE_TEST
  .coveragerc
  CHANGELOG.md
  baybe/utils/plotting.py
  docs/scripts/utils.py
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/botorch_analytical_dark.svg
  examples/Backtesting/botorch_analytical_light.svg
  examples/plotting_themes.json
  mypy.ini
  pyproject.toml
  tox.ini
Labels: documentation

#134 Configurable Cache Dirs
  CHANGELOG.md
  baybe/utils/chemistry.py
Labels: bug, enhancement

#133 Hotfix: Fallback for Windows-related getuser() issue
  CHANGELOG.md
  baybe/telemetry.py
Labels: bug

#136 Fix hybrid metadata
  CHANGELOG.md
  baybe/recommenders/base.py
Labels: enhancement

#138 Hotfix: Telemetry Was Accidentally Disabled
  CHANGELOG.md
  baybe/telemetry.py
Labels: bug

#139 Add line wrap for examples in documentation
  CHANGELOG.md
  docs/scripts/utils.py
Labels: bug, documentation

#137 Nonzero simplex parameter control
  CHANGELOG.md
  baybe/searchspace/discrete.py
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
Labels: new feature

#124 Include pretty printing for search spaces
  CHANGELOG.md
  CONTRIBUTORS.md
  baybe/constraints/base.py
  baybe/parameters/base.py
  baybe/parameters/numerical.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/utils/dataframe.py
Labels: enhancement

#141 Remove progress bar in examples
  CHANGELOG.md
  docs/scripts/utils.py
Labels: documentation

#144 Enable repo reminders
  .github/workflows/ci.yml
  .github/workflows/regular.yml
  CHANGELOG.md
Labels: repo

#147 Mypy for recommenders
  CHANGELOG.md
  baybe/recommenders/deprecation.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/sequential_greedy.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  mypy.ini
Labels: typing

#148 Consolidate recommender / strat user guides and examples
  baybe/recommenders/pure/__init__.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  docs/userguide/campaigns.md
  docs/userguide/recommender.md
  docs/userguide/recommenders.md
  docs/userguide/searchspace.md
  docs/userguide/strategies.md
  docs/userguide/userguide.md
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/hybrid.py
  examples/Basics/Basics_Header.md
  examples/Basics/recommenders.py
  examples/Searchspaces/hybrid_space.py
  streamlit/initial_recommender.py
  tests/docs/test_examples.py
  tests/test_iterations.py
Labels: documentation, enhancement

#150 Include SMOKE_TEST in examples
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/hybrid.py
  examples/Backtesting/impute_mode.py
  examples/Backtesting/multi_target.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
Labels: documentation

#149 Release 0.7.4
  CHANGELOG.md
  baybe/campaign.py
Labels: repo

#119 Lazy loading torch - part 1
  CHANGELOG.md
  baybe/constraints/base.py
  baybe/scaler.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
Labels: enhancement
