Repository emdgroup/baybe, pull requests merged in 2024-01, with the labels that each got.

#72 Finish Constraints User Guide
  CHANGELOG.md
  baybe/constraints/discrete.py
  docs/userguide/constraints.md
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  tests/conftest.py
  tests/test_constraints_discrete.py
Labels: documentation

#77 Formatting test for user guide code blocks
  CHANGELOG.md
  README.md
  docs/userguide/constraints.md
  docs/userguide/parameters.md
  pyproject.toml
  tests/docs/test_docs.py
  tests/docs/utils.py
Labels: documentation

#75 Use pydoclint as flake8 plugin
  .pre-commit-config.yaml
  CHANGELOG.md
  baybe/parameters/validation.py
  pydoclint.toml
  pyproject.toml
Labels: repo

#81 Adjust margins in documentation
  CHANGELOG.md
  docs/_static/custom.css
Labels: documentation

#82 Build but do not execute examples when ignoring them
  .github/workflows/ci.yml
  CHANGELOG.md
  docs/scripts/convert_code_to_documentation.py
Labels: documentation

#61 Campaign user guide
  CHANGELOG.md
  docs/userguide/campaigns.md
  examples/Basics/campaign.py
  tests/conftest.py
  tests/docs/test_docs.py
Labels: documentation

#85 Interval convenience deserialization
  CHANGELOG.md
  baybe/utils/interval.py
  tests/hypothesis_strategies/alternative_creation/test_intervals.py
Labels: enhancement

#90 Change docs publishing trigger
  .github/workflows/docs.yml
Labels: documentation, repo

#86 Config and serialization enhancement
  CHANGELOG.md
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/deprecation.py
  baybe/objective.py
  baybe/parameters/base.py
  baybe/parameters/utils.py
  baybe/recommenders/base.py
  baybe/searchspace/__init__.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/serialization/__init__.py
  baybe/serialization/core.py
  baybe/serialization/mixin.py
  baybe/serialization/utils.py
  baybe/strategies/base.py
  baybe/strategies/composite.py
  baybe/strategies/deprecation.py
  baybe/surrogates/base.py
  baybe/targets/base.py
  baybe/targets/numerical.py
  baybe/utils/__init__.py
  baybe/utils/interval.py
  docs/conf.py
  docs/userguide/campaigns.md
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  mypy.ini
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
  tests/hypothesis_strategies/dataframes.py
  tests/serialization/test_dataframe_serialization.py
  tests/serialization/test_searchspace_serialization.py
  tests/test_deprecations.py
  tox.ini
Labels: enhancement

#98 Release 0.7.2
  CHANGELOG.md
Labels: repo

#87 Lazy-loading chemistry dependencies
  CHANGELOG.md
  CONTRIBUTORS.md
  baybe/exceptions.py
  baybe/parameters/substance.py
  baybe/utils/__init__.py
  baybe/utils/chemistry.py
  tests/conftest.py
  tests/docs/test_examples.py
  tests/test_substance_parameter.py
Labels: repo

#83 Minor doc tweaks
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/faq.md
  docs/index.md
  docs/known_issues.md
  docs/misc/license_link.md
  docs/scripts/convert_code_to_documentation.py
  docs/templates/custom-class-template.rst
  docs/userguide/campaigns.md
  docs/userguide/constraints.md
  docs/userguide/parameters.md
  docs/userguide/strategies.md
  docs/userguide/userguide.md
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  pyproject.toml
Labels: documentation

#93 Misc MyPy Activations
  CHANGELOG.md
  baybe/campaign.py
  baybe/constraints/conditions.py
  baybe/constraints/discrete.py
  baybe/telemetry.py
  baybe/utils/basic.py
  baybe/utils/numeric.py
  baybe/utils/sampling_algorithms.py
  docs/conf.py
  mypy.ini
  pyproject.toml
Labels: typing

#95 Reorder README sections and print dataframe
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
Labels: documentation

#102 Remove botorch wrapper from namespace
  CHANGELOG.md
  baybe/utils/__init__.py
  examples/Backtesting/botorch_analytical.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Searchspaces/discrete_space.py
  examples/Searchspaces/hybrid_space.py
Labels: enhancement, repo
