Repository emdgroup/baybe, pull requests merged in 2024-04, with the labels that each got.

#189 Emojification
  README.md
Labels: documentation

#173 Lazy load DTypeFloatTorch
  CHANGELOG.md
  baybe/constraints/base.py
  baybe/objective.py
  baybe/surrogates/custom.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
  baybe/utils/numerical.py
  baybe/utils/torch.py
Labels: enhancement

#187 Fix: n_task_params now evaluates to 1 if task_idx == 0
  CHANGELOG.md
  baybe/surrogates/gaussian_process.py
Labels: bug

#190 Acquisition package
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/adapter.py
  baybe/acquisition/partial.py
  mypy.ini
Labels: repo

#177 Mypy for search spaces
  CHANGELOG.md
  baybe/campaign.py
  baybe/constraints/base.py
  baybe/constraints/validation.py
  baybe/parameters/utils.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/searchspace/validation.py
  baybe/telemetry.py
  baybe/utils/basic.py
  baybe/utils/dataframe.py
  baybe/utils/interval.py
  mypy.ini
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
  tests/test_searchspace.py
Labels: typing

#165 Lazy load `torch` in surrogates
  CHANGELOG.md
  baybe/acquisition/partial.py
  baybe/acquisition/utils.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process.py
  baybe/surrogates/linear.py
  baybe/surrogates/naive.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/surrogates/utils.py
Labels: enhancement

#188 Objective classes
  CHANGELOG.md
  README.md
  baybe/campaign.py
  baybe/objective.py
  baybe/objectives/__init__.py
  baybe/objectives/base.py
  baybe/objectives/deprecation.py
  baybe/objectives/desirability.py
  baybe/objectives/enum.py
  baybe/objectives/single.py
  baybe/recommenders/deprecation.py
  baybe/targets/base.py
  baybe/targets/deprecation.py
  baybe/targets/numerical.py
  baybe/utils/numerical.py
  docs/templates/custom-module-template.rst
  docs/userguide/objective.md
  examples/Backtesting/botorch_analytical.py
  examples/Backtesting/custom_analytical.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/hybrid.py
  examples/Backtesting/impute_mode.py
  examples/Backtesting/multi_target.py
  examples/Basics/campaign.py
  examples/Basics/recommenders.py
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Constraints_Discrete/custom_constraints.py
  examples/Constraints_Discrete/dependency_constraints.py
  examples/Constraints_Discrete/exclusion_constraints.py
  examples/Constraints_Discrete/mixture_constraints.py
  examples/Constraints_Discrete/prodsum_constraints.py
  examples/Custom_Surrogates/custom_architecture_sklearn.py
  examples/Custom_Surrogates/custom_architecture_torch.py
  examples/Custom_Surrogates/custom_pretrained.py
  examples/Custom_Surrogates/surrogate_params.py
  examples/Multi_Target/desirability.py
  examples/Searchspaces/continuous_space_botorch_function.py
  examples/Searchspaces/continuous_space_custom_function.py
  examples/Searchspaces/discrete_space.py
  examples/Searchspaces/hybrid_space.py
  examples/Serialization/basic_serialization.py
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/basic_transfer_learning.py
  mypy.ini
  tests/conftest.py
  tests/serialization/test_objective_serialization.py
  tests/test_deprecations.py
  tests/test_objective.py
Labels: enhancement

#191 Acquisition function classes
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  baybe/acquisition/adapter.py
  baybe/acquisition/base.py
  baybe/acquisition/partial.py
  baybe/acquisition/utils.py
  baybe/recommenders/base.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/bayesian/sequential_greedy.py
  baybe/serialization/core.py
  examples/Backtesting/custom_analytical.py
  examples/Basics/recommenders.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  tests/conftest.py
  tests/hypothesis_strategies/acquisition.py
  tests/hypothesis_strategies/alternative_creation/test_acquisition.py
  tests/serialization/test_acquisition_serialization.py
  tests/test_acquisition.py
  tests/test_deprecations.py
  tests/test_iterations.py
Labels: new feature

#196 Skeleton for kernels
  CHANGELOG.md
  baybe/kernels/__init__.py
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/surrogates/gaussian_process.py
  baybe/utils/basic.py
  examples/Basics/recommenders.py
  tests/hypothesis_strategies/alternative_creation/test_kernels.py
  tests/hypothesis_strategies/kernels.py
  tests/serialization/test_kernel_serialization.py
Labels: new feature

#197 Hypothesis for objectives
  CHANGELOG.md
  baybe/objectives/base.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  tests/hypothesis_strategies/alternative_creation/test_searchspace.py
  tests/hypothesis_strategies/objectives.py
  tests/hypothesis_strategies/parameters.py
  tests/hypothesis_strategies/targets.py
  tests/hypothesis_strategies/utils.py
  tests/serialization/test_objective_serialization.py
  tests/serialization/test_parameter_serialization.py
  tests/serialization/test_target_serialization.py
  tests/validation/test_objective_validation.py
Labels: tests

#202 Fix lookup bug in simulation
  CHANGELOG.md
  baybe/simulation.py
Labels: bug

#178 Hypothesis for constraints
  CHANGELOG.md
  tests/hypothesis_strategies/constraints.py
  tests/hypothesis_strategies/parameters.py
  tests/serialization/test_constraint_serialization.py
Labels: tests

#208 Hotfix for match mode simulation
  CHANGELOG.md
  baybe/simulation.py
  baybe/utils/numerical.py
  tests/test_utils.py
Labels: bug

#201 Update objective user guide
  CHANGELOG.md
  README.md
  docs/userguide/campaigns.md
  docs/userguide/objective.md
  examples/Multi_Target/Multi_Target_Header.md
  tests/docs/test_docs.py
Labels: documentation

#205 Telemetry changes
  CHANGELOG.md
  README.md
  baybe/telemetry.py
Labels: enhancement

#182 Use tox-uv
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/regular.yml
  CHANGELOG.md
  pyproject.toml
Labels: repo

#198 Expire 0.6.x deprecations
  CHANGELOG.md
  baybe/__init__.py
  baybe/deprecation.py
  baybe/strategies/__init__.py
  baybe/strategies/deprecation.py
  baybe/surrogate.py
  baybe/targets/__init__.py
  baybe/targets/deprecation.py
  docs/templates/custom-module-template.rst
  mypy.ini
  tests/test_deprecations.py
Labels: deprecation, release

#206 `torch` lazy loading
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/base.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/bayesian/sequential_greedy.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process.py
  baybe/surrogates/utils.py
  baybe/utils/dataframe.py
  streamlit/surrogate_models.py
  tests/test_imports.py
  tox.ini
Labels: enhancement, refactor

#210 Create `simulation` subpackage
  .coveragerc
  CHANGELOG.md
  baybe/simulation.py
  baybe/simulation/__init__.py
  baybe/simulation/core.py
  baybe/simulation/lookup.py
  baybe/simulation/scenarios.py
  baybe/simulation/transfer_learning.py
  docs/userguide/simulation.md
  examples/Backtesting/botorch_analytical.py
  examples/Transfer_Learning/backtesting.py
  mypy.ini
Labels: refactor

#219 Custom kernel priors
  CHANGELOG.md
  baybe/kernels/base.py
  baybe/kernels/basic.py
  baybe/kernels/priors/__init__.py
  baybe/kernels/priors/base.py
  baybe/kernels/priors/basic.py
  baybe/surrogates/gaussian_process.py
  tests/hypothesis_strategies/kernels.py
  tests/hypothesis_strategies/priors.py
  tests/serialization/test_prior_serialization.py
Labels: enhancement
