Repository emdgroup/baybe, pull requests merged in 2025-01, with the labels that each got.

#462 Hotfix: Minimization with bounds properly minimize targets
  CHANGELOG.md
  baybe/objectives/single.py
  tests/test_objective.py
Labels: bug

#457 Simplify and extend meta recommender logic
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/meta/sequential.py
  tests/serialization/test_meta_recommender_serialization.py
  tests/test_deprecations.py
  tests/test_meta_recommenders.py
Labels: enhancement, refactor

#465 Fix minimization of improvement-based MC acquisition functions
  CHANGELOG.md
  baybe/acquisition/base.py
  tests/integration/test_minimization.py
Labels: bug

#463 Maintain row order after cross join
  CHANGELOG.md
  docs/userguide/envvars.md
  tests/constraints/test_constraints_polars.py
Labels: enhancement

#423 Move `allow_*` flags to `Campaign`
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/campaign.py
  baybe/exceptions.py
  baybe/recommenders/base.py
  baybe/recommenders/naive.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/_annotated.py
  baybe/searchspace/_filtered.py
  baybe/searchspace/discrete.py
  baybe/utils/basic.py
  docs/conf.py
  docs/faq.md
  docs/index.md
  docs/userguide/async.md
  docs/userguide/campaigns.md
  docs/userguide/getting_recommendations.md
  docs/userguide/recommenders.md
  docs/userguide/userguide.md
  examples/Basics/recommenders.py
  examples/Custom_Hooks/campaign_stopping.py
  examples/Multi_Armed_Bandit/bernoulli_multi_armed_bandit.py
  examples/Serialization/create_from_config.py
  examples/Serialization/validate_config.py
  pyproject.toml
  tests/conftest.py
  tests/simulate_telemetry.py
  tests/test_campaign.py
  tests/test_deprecations.py
  tests/test_integration.py
  tests/test_iterations.py
  tests/test_pending_experiments.py
Labels: enhancement, refactor

#466 Insights User Guide
  CHANGELOG.md
  baybe/insights/shap.py
  docs/_static/insights/shap_bar_comp_rep.svg
  docs/_static/insights/shap_bar_exp_rep.svg
  docs/_static/insights/shap_bar_lime.svg
  docs/_static/insights/shap_beeswarm_exp_rep.svg
  docs/_static/insights/shap_force.svg
  docs/conf.py
  docs/userguide/insights.md
  docs/userguide/userguide.md
Labels: documentation

#470 Release 0.12.0
  .lockfiles/py310-dev.lock
  CHANGELOG.md
Labels: release

#471 Reset flag default value
  CHANGELOG.md
  baybe/campaign.py
Labels: release, hotfix

#472 Improve GP Fit
  CHANGELOG.md
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/naive.py
Labels: enhancement, release
