Repository emdgroup/baybe, pull requests merged in 2025-05, with the labels that each got.

#554 Fix guard clause
  CHANGELOG.md
  baybe/acquisition/_builder.py
  streamlit/surrogate_models.py
Labels: bug

#555 Make import of deprecated ONNX function robust
  baybe/_optional/onnx.py
  mypy.ini
  tests/conftest.py
Labels: repo, hotfix

#414 Enable Python 3.13
  .github/workflows/ci.yml
  .github/workflows/regular.yml
  .github/workflows/release.yml
  CHANGELOG.md
  CONTRIBUTING.md
  baybe/_optional/onnx.py
  mypy.ini
  pyproject.toml
  tests/README.md
  tests/conftest.py
  tests/docs/test_examples.py
  tests/serialization/test_surrogate_serialization.py
  tests/test_custom_surrogate.py
  tox.ini
Labels: repo

#559 Add missing decorator return type
  CHANGELOG.md
  baybe/surrogates/utils.py
Labels: typing

#491 Add benchmarks
  .github/workflows/manual_benchmark.yml
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/simulation/lookup.py
  benchmarks/data/aryl_halide/data.csv
  benchmarks/data/direct_arylation/data.csv
  benchmarks/data/utils.py
  benchmarks/domains/__init__.py
  benchmarks/domains/direct_arylation/__init__.py
  benchmarks/domains/direct_arylation/direct_arylation_multi_batch.py
  benchmarks/domains/direct_arylation/direct_arylation_single_batch.py
  benchmarks/domains/hartmann/hartmann_3d.py
  benchmarks/domains/hartmann/hartmann_3d_discretized.py
  benchmarks/domains/hartmann/hartmann_6d.py
  benchmarks/domains/synthetic_2C1D_1C.py
  benchmarks/domains/transfer_learning/aryl_halides/__init__.py
  benchmarks/domains/transfer_learning/aryl_halides/base.py
  benchmarks/domains/transfer_learning/aryl_halides/sou_CT_I_tar_BM.py
  benchmarks/domains/transfer_learning/aryl_halides/sou_CT_tar_IM.py
  benchmarks/domains/transfer_learning/aryl_halides/sout_IP_tar_CP.py
  benchmarks/domains/transfer_learning/direct_arylation/__init__.py
  benchmarks/domains/transfer_learning/direct_arylation/temperature_tl.py
  benchmarks/domains/transfer_learning/easom/__init__.py
  benchmarks/domains/transfer_learning/easom/easom_tl_47_negate_noise5.py
  benchmarks/domains/transfer_learning/hartmann/__init__.py
  benchmarks/domains/transfer_learning/hartmann/hartmann_tl_3_20_15.py
  benchmarks/domains/transfer_learning/michalewicz/__init__.py
  benchmarks/domains/transfer_learning/michalewicz/michalewicz_tl_continuous.py
  examples/Backtesting/full_initial_data.py
  examples/Backtesting/full_lookup.py
  examples/Backtesting/lookup.xlsx
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Surrogates/custom_pretrained.py
  pyproject.toml
  tests/docs/test_examples.py
Labels: benchmarking
