Repository emdgroup/baybe, pull requests merged in 2025-02, with the labels that each got.

#474 Fix Substance Encodings
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/constraints/continuous.py
  baybe/parameters/enum.py
  baybe/utils/chemistry.py
  docs/conf.py
  examples/Transfer_Learning/backtesting.py
  pyproject.toml
  tests/conftest.py
  tests/test_substance_parameter.py
Labels: bug, documentation, enhancement

#478 Serialize python env and version data
  benchmarks/result/result.py
Labels: bug, benchmarking

#477 Refactor benchmark architecture
  .lockfiles/py310-dev.lock
  benchmarks/__init__.py
  benchmarks/definition/__init__.py
  benchmarks/definition/base.py
  benchmarks/definition/config.py
  benchmarks/definition/convergence.py
  benchmarks/domains/__init__.py
  benchmarks/domains/synthetic_2C1D_1C.py
  benchmarks/persistence/persistence.py
  benchmarks/result/metadata.py
  benchmarks/result/result.py
  pyproject.toml
Labels: refactor

#479 Refactor ACQF indicators
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  baybe/recommenders/pure/bayesian/botorch.py
  docs/conf.py
  docs/userguide/active_learning.md
  pyproject.toml
  tests/hypothesis_strategies/acquisition.py
  tests/test_iterations.py
  tests/test_pending_experiments.py
Labels: bug, refactor

#481 XFail bugged test case
  tests/test_kernels.py
Labels: repo

#486 Fix SHAP Plot Tests
  tests/insights/test_shap.py
Labels: tests

#456 Rework validation for `measurements` and `pending_experiments`
  baybe/campaign.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/recommenders/pure/nonpredictive/base.py
  baybe/simulation/core.py
  baybe/telemetry.py
  baybe/utils/dataframe.py
  baybe/utils/validation.py
  tests/conftest.py
  tests/test_input_output.py
  tests/test_pending_experiments.py
  tests/test_surrogate.py
Labels: enhancement
