Repository emdgroup/baybe, pull requests merged in 2025-04, with the labels that each got.

#527 Fix lockfile creation for uv>=0.6.0
  tox.ini
Labels: repo

#528 Drop funcy dependency
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/constraints/conditions.py
  pyproject.toml
  streamlit/surrogate_models.py
Labels: repo

#532 Add qLogNParEGO
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
Labels: new feature

#507 More hypervolume acquisition functions
  CHANGELOG.md
  baybe/acquisition/__init__.py
  baybe/acquisition/_builder.py
  baybe/acquisition/acqfs.py
  docs/conf.py
  tests/hypothesis_strategies/acquisition.py
Labels: new feature

#529 Make `ngboost` optional
  CHANGELOG.md
  README.md
  baybe/_optional/info.py
  baybe/_optional/ngboost.py
  baybe/campaign.py
  baybe/objectives/desirability.py
  baybe/objectives/single.py
  baybe/recommenders/meta/sequential.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/bandit.py
  baybe/surrogates/base.py
  baybe/surrogates/custom.py
  baybe/surrogates/gaussian_process/core.py
  baybe/surrogates/linear.py
  baybe/surrogates/ngboost.py
  baybe/surrogates/random_forest.py
  baybe/utils/conversion.py
  docs/scripts/build_examples.py
  examples/Backtesting/custom_blackbox.py
  examples/Backtesting/full_lookup.py
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Hooks/probability_of_improvement.py
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/basic_transfer_learning.py
  examples/utils.py
  pyproject.toml
  tests/docs/test_examples.py
  tests/insights/test_shap.py
  tests/serialization/test_surrogate_serialization.py
  tests/test_iterations.py
Labels: repo

#536 Posterior Stats: Catch No Measurements Case
  baybe/campaign.py
  baybe/exceptions.py
  baybe/insights/shap.py
  tests/insights/test_shap.py
Labels: enhancement

#530 Make `scikit-learn-extra` optional
  CHANGELOG.md
  baybe/_optional/chem.py
  baybe/_optional/info.py
  baybe/_optional/insights.py
  baybe/_optional/ngboost.py
  baybe/_optional/onnx.py
  baybe/_optional/polars.py
  baybe/_optional/simulation.py
  baybe/_optional/sklearn_extra.py
  baybe/exceptions.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  pyproject.toml
  tests/test_integration.py
  tests/test_iterations.py
  tests/test_pending_experiments.py
Labels: repo

#526 Make `setuptools-scm` optional
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  README.md
  baybe/__init__.py
  pyproject.toml
Labels: repo

#509 Acquisition utility method
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/campaign.py
  baybe/recommenders/pure/bayesian/base.py
  docs/userguide/campaigns.md
  examples/Custom_Hooks/campaign_stopping.py
  examples/Custom_Hooks/probability_of_improvement.py
  tests/docs/test_docs.py
  tests/test_campaign.py
Labels: new feature

#540 Remove xfail for fixed SHAP case
  tests/insights/test_shap.py
Labels: bug

#497 Expire 0.9.* deprecations
  CHANGELOG.md
  baybe/acquisition/base.py
  baybe/objective.py
  baybe/objectives/base.py
  baybe/objectives/deprecation.py
  baybe/recommenders/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/targets/base.py
  docs/userguide/objectives.md
  examples/Transfer_Learning/backtesting.py
  examples/Transfer_Learning/basic_transfer_learning.py
  tests/conftest.py
  tests/simulate_telemetry.py
  tests/test_deprecations.py
Labels: deprecation

#514 Enable Partial Measurements
  CHANGELOG.md
  README.md
  baybe/acquisition/_builder.py
  baybe/acquisition/acqfs.py
  baybe/campaign.py
  baybe/exceptions.py
  baybe/surrogates/base.py
  baybe/surrogates/composite.py
  baybe/utils/dataframe.py
  baybe/utils/validation.py
  docs/userguide/async.md
  docs/userguide/objectives.md
  docs/userguide/surrogates.md
  tests/conftest.py
  tests/test_campaign.py
  tests/test_input_output.py
  tests/test_partial_measurements.py
  tests/utils/test_dataframe.py
Labels: new feature

#538 Integrate KMedoids
  .lockfiles/py310-dev.lock
  CHANGELOG.md
  baybe/_optional/info.py
  baybe/_optional/sklearn_extra.py
  baybe/recommenders/pure/nonpredictive/clustering.py
  baybe/utils/clustering_algorithms/__init__.py
  baybe/utils/clustering_algorithms/third_party/__init__.py
  baybe/utils/clustering_algorithms/third_party/kmedoids.py
  docs/conf.py
  docs/known_issues.md
  mypy.ini
  pyproject.toml
  tests/test_pending_experiments.py
Labels: enhancement, repo

#541 Release 0.13.0
  CHANGELOG.md
Labels: release

#519 Tie breaking for FPS
  CHANGELOG.md
  baybe/recommenders/pure/nonpredictive/sampling.py
  baybe/utils/sampling_algorithms.py
  tests/utils/test_sampling_algorithms.py
Labels: enhancement

#543 Enable parallel execution of scenarios
  CHANGELOG.md
  baybe/simulation/scenarios.py
Labels: enhancement
