Repository emdgroup/baybe, pull requests merged in 2025-03, with the labels that each got.

#498 Increase timeout for benchmark test to 1440 minutes (24 hours)
  .github/workflows/manual_benchmark.yml
Labels: benchmarking

#499 Add logging to indicate currently running benchmark and its runtime
  benchmarks/definition/base.py
Labels: benchmarking

#489 Vectorize `fuzzy_row_match`
  CHANGELOG.md
  baybe/exceptions.py
  baybe/utils/dataframe.py
  tests/utils/test_dataframe.py
Labels: enhancement

#501 Disable pre-commit.ci autofixing
  .pre-commit-config.yaml
Labels: repo

#301 Botorch with cardinality constraint via sampling
  CHANGELOG.md
  README.md
  baybe/constraints/continuous.py
  baybe/constraints/utils.py
  baybe/constraints/validation.py
  baybe/exceptions.py
  baybe/parameters/numerical.py
  baybe/parameters/utils.py
  baybe/recommenders/pure/bayesian/botorch.py
  baybe/searchspace/continuous.py
  tests/constraints/test_cardinality_constraint_continuous.py
  tests/test_searchspace.py
  tests/utils/test_parameters.py
Labels: new feature

#505 Fix Pareto example plot export
  examples/Multi_Target/pareto.py
Labels: bug

#506 Fix serialization errors on 3.12
  baybe/surrogates/composite.py
Labels: bug

#496 User guide for cardinality constraints
  CHANGELOG.md
  docs/userguide/constraints.md
Labels: documentation

#495 Generalize `active_values`
  CHANGELOG.md
  baybe/campaign.py
  baybe/parameters/base.py
  baybe/parameters/categorical.py
  baybe/parameters/custom.py
  baybe/parameters/substance.py
  baybe/searchspace/_filtered.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/surrogates/base.py
  baybe/surrogates/gaussian_process/core.py
  baybe/utils/dataframe.py
  docs/conf.py
  docs/userguide/envvars.md
  docs/userguide/getting_recommendations.md
  docs/userguide/parameters.md
  docs/userguide/targets.md
  tests/conftest.py
  tests/constraints/test_constraints_discrete.py
  tests/constraints/test_constraints_polars.py
  tests/hypothesis_strategies/parameters.py
  tests/serialization/test_dataframe_serialization.py
  tests/serialization/test_naive_hybrid_serialization.py
  tests/serialization/test_searchspace_serialization.py
  tests/test_continuous.py
  tests/test_custom_surrogate.py
  tests/test_iterations.py
  tests/test_searchspace.py
  tests/utils/test_dataframe.py
  tests/validation/test_parameter_validation.py
Labels: enhancement, new feature

#502 Pipeline benchmark parallelization
  .github/workflows/manual_benchmark.yml
  CHANGELOG.md
  benchmarks/README.md
  benchmarks/__main__.py
  benchmarks/domains/__init__.py
Labels: benchmarking

#510 Xfail bugged SHAP plot tests
  tests/insights/test_shap.py
Labels: bug

#511 Fix converter typing
  baybe/constraints/conditions.py
  baybe/kernels/composite.py
  baybe/parameters/base.py
Labels: typing

#490 Acquisition function builder
  CHANGELOG.md
  baybe/acquisition/_builder.py
  baybe/acquisition/acqfs.py
  baybe/acquisition/base.py
  tests/hypothesis_strategies/acquisition.py
  tests/test_imports.py
Labels: enhancement, refactor

#504 Add `Campaign.posterior_stats`
  CHANGELOG.md
  baybe/campaign.py
  baybe/constraints/discrete.py
  baybe/surrogates/base.py
  baybe/surrogates/composite.py
  docs/userguide/campaigns.md
  tests/conftest.py
  tests/docs/test_docs.py
  tests/test_campaign.py
Labels: new feature
