Repository emdgroup/baybe, pull requests merged in 2025-08, with the labels that each got.

#599 Composite transformations
  CHANGELOG.md
  baybe/objectives/desirability.py
  baybe/targets/numerical.py
  baybe/transformations/__init__.py
  baybe/transformations/base.py
  baybe/transformations/basic.py
  baybe/transformations/composite.py
  baybe/transformations/utils.py
  baybe/utils/basic.py
  tests/hypothesis_strategies/transformations.py
  tests/serialization/test_objective_serialization.py
  tests/serialization/test_target_serialization.py
  tests/serialization/test_transformation_serialization.py
  tests/test_deprecations.py
  tests/test_objective.py
  tests/test_targets.py
  tests/test_transformations.py
  tests/validation/test_objective_validation.py
Labels: new feature

#613 Lockfile check via pre-commit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  tox.ini
Labels: repo

#576 Fix: Set random seed within benchmark
  CHANGELOG.md
  benchmarks/definition/base.py
  benchmarks/domains/direct_arylation/direct_arylation_multi_batch.py
  benchmarks/domains/direct_arylation/direct_arylation_single_batch.py
  benchmarks/domains/hartmann/hartmann_3d.py
  benchmarks/domains/hartmann/hartmann_3d_discretized.py
  benchmarks/domains/hartmann/hartmann_6d.py
  benchmarks/domains/synthetic_2C1D_1C.py
  benchmarks/domains/transfer_learning/aryl_halides/base.py
  benchmarks/domains/transfer_learning/direct_arylation/temperature_tl.py
  benchmarks/domains/transfer_learning/easom/easom_tl_47_negate_noise5.py
  benchmarks/domains/transfer_learning/hartmann/hartmann_tl_3_20_15.py
  benchmarks/domains/transfer_learning/michalewicz/michalewicz_tl_continuous.py
Labels: bug, benchmarking

#617 Use `importlib.metadata`
  benchmarks/result/result.py
Labels: typing

#619 Feature/base tl regr benchmark
  benchmarks/__init__.py
  benchmarks/definition/__init__.py
  benchmarks/definition/regression.py
Labels: benchmarking

#627 Bring back downloads badge
  README.md
Labels: documentation

#589 Expire 0.10.* deprecations
  CHANGELOG.md
  baybe/recommenders/__init__.py
  baybe/recommenders/pure/__init__.py
  baybe/recommenders/pure/bayesian/__init__.py
  baybe/recommenders/pure/bayesian/sequential_greedy.py
  baybe/searchspace/continuous.py
  baybe/searchspace/core.py
  baybe/searchspace/discrete.py
  baybe/utils/dataframe.py
  tests/integration/test_minimization.py
  tests/test_deprecations.py
Labels: deprecation

#624 Harmonize `float` Related Converters and Validators in Constraints and Conditions
  CHANGELOG.md
  baybe/constraints/conditions.py
  baybe/constraints/continuous.py
  docs/userguide/constraints.md
  examples/Constraints_Continuous/hybrid_space.py
  examples/Constraints_Continuous/linear_constraints.py
  examples/Mixtures/traditional.py
  tests/hypothesis_strategies/constraints.py
Labels: bug

#623 Forbid Overlap in Target and Parameter Names
  CHANGELOG.md
  baybe/campaign.py
  baybe/recommenders/meta/base.py
  baybe/recommenders/pure/base.py
  baybe/recommenders/pure/bayesian/base.py
  baybe/utils/validation.py
  tests/validation/test_campaign_validation.py
Labels: bug
